name: Build .NET Blazor App

on: 
  workflow_call:
    inputs:
      blazorAppName:
        description: 'Name of the blazor app'     
        required: true
        type: string
      solutionName:
        description: 'Name of the solution'     
        required: true
        type: string
      dotNet:
        description: 'Version of the .Net runtime'     
        required: true
        type: string
      blazorWasm:
        description: 'The Blazor workload to install.'
        required: true
        type: string
      environment:
          description: 'Define the  Environment: Prod, Acc, Test, Dev'     
          required: true
          type: string      
      testFilter:
        description: 'Add a filter expression when running the unit test projects'
        required: true
        type: string
     
env:
  blazorRoot: './src/FE/${{ github.event.inputs.blazorAppName }}/${{ github.event.inputs.solutionName }}.${{ github.event.inputs.blazorAppName }}/'
  host: './src/FE/${{ github.event.inputs.blazorAppName }}/${{ github.event.inputs.solutionName }}.${{ github.event.inputs.blazorAppName }}/${{ github.event.inputs.solutionName }}.${{ github.event.inputs.blazorAppName }}.csproj'
  buildConfiguration: 'Release'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: ${{ github.event.inputs.dotNet }}

      - name: Echo Download wasm tool
        run: |
          dotnet workload install ${{ github.event.inputs.blazorWasm }}

      - uses: actions/checkout@v3
      - name: Setup .NET Core 8 for the shared domain class
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 8.0.100-rc.2.23502.2

      - name: Echo testFilter
        run: |
          echo "testFilter parameter is set to : ${{ inputs.testFilter }}"

      - name: Run Test projects matching *UnitTest.csproj
        if: inputs.testFilter == ''
        run: |
            Get-ChildItem -Filter *.${{ inputs.blazorAppName }}.*UnitTest.csproj -Recurse | ForEach-Object { dotnet test $_.FullName -c ${{ env.buildConfiguration }}  }
        shell: pwsh            

      - name: Run Test projects matching *UnitTest.csproj with filter ${{ inputs.testFilter }}
        if: inputs.testFilter != ''
        run: |
            Get-ChildItem -Filter *.${{ inputs.blazorAppName }}.*UnitTest.csproj -Recurse | ForEach-Object { dotnet test $_.FullName -c ${{ env.buildConfiguration }} --filter '${{ inputs.testFilter }}' }
        shell: pwsh            

      - name: Build
        run: dotnet publish  ${{ env.host }}  -c ${{ env.buildConfiguration }} -o ./Service

      # - name: Substitue nginx file
      #   uses: bluwy/substitute-string-action@v1
      #   id: sub
      #   with:
      #     _input-file: './src/FE/${{ github.event.inputs.blazorAppName }}/nginx.conf'
      #     _format-key: '%%key%%'
      #     Environment: ${{ inputs.Environment }}
      
      # - name: Create nginx file
      #   uses: DamianReeves/write-file-action@v1.0
      #   with:
      #     path: ./Service/nginx.conf
      #     contents: ${{ steps.sub.outputs.result }}
      #     write-mode: append

      - name: Copy deploy file
        run: cp ./src/FE/${{ github.event.inputs.blazorAppName }}/deploy.yml ./deploy.yml  
      
      - name: Copy Docker file
        run: cp ./src/FE/${{ github.event.inputs.blazorAppName }}/Dockerfile ./Dockerfile          

      - name: Move settings files to a config folder.
        run:  | 
            mkdir -p ./Service/Configs
            mv ./Service/wwwroot/appsettings*.json ./Service/Configs  

      - name: Move nginx.conf file to a config folder.
        run:  | 
            mkdir -p ./Service/Configs
            mv ./src/FE/${{ github.event.inputs.blazorAppName }}/nginx.conf ./Service/Configs 

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ./Service
            ./Dockerfile
            ./deploy.yml
          retention-days: 1