name: Build a Docker image

on: 
  workflow_call:
    inputs:
      DockerContainer:
        description: 'Docker container used to store the images'
        required: true
        type: string    
      DockerImage:
        description: 'Docker image name use to store in a container with no version Tag'
        required: true
        type: string
      DockerImageTagVersion:
        description: 'version Tag'
        required: true
        type: string     
      DockerEnvironmentTagVersion:
        description: 'Environment Tag: Dev - Test - Acc - Prod'
        required: true
        type: string            
      CR_Registry:
        description: 'Name of the container registry'     
        required: true
        type: string
      CR_User:
        description: 'container registry name'     
        required: true
        type: string        
    secrets:
      CR_Password:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
     fullImagePath: ${{ steps.imageTag.outputs.fullImagePath }}
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: artifact

      - name: Save artifacts
        uses: actions/upload-artifact@v6
        with:
          name: configs
          path: |
            ./Service/Configs
            ./deploy.yml
          retention-days: 90
          
      - name: Remove Folder
        run: rm -rf ./Service/Configs
  
      - name: Ensure DockerImage name is in lower case!
        run: echo "DockerImage=$(echo ${{ inputs.DockerImage }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        id: DockerImageToLower

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.CR_Registry }}
          username: ${{ inputs.CR_User }}
          password: ${{ secrets.CR_Password }}

      - name: Build and publish the docker image.
        run: |
          docker build ./Service -f ./Dockerfile -t ${{ format('{0}:{1}', steps.DockerImageToLower.outputs.DockerImage, inputs.DockerImageTagVersion) }}
          docker push ${{ format('{0}:{1}', steps.DockerImageToLower.outputs.DockerImage, inputs.DockerImageTagVersion) }} 

      - name: Tag built container with Azure Container Registry url
        run: docker tag ${{ format('{0}:{1}', steps.DockerImageToLower.outputs.DockerImage, inputs.DockerImageTagVersion) }} ${{ format('{0}:{1}', steps.DockerImageToLower.outputs.DockerImage, inputs.DockerEnvironmentTagVersion) }}

      - name: Push built container to Azure Container Registry
        run: docker push ${{ format('{0}:{1}', steps.DockerImageToLower.outputs.DockerImage, inputs.DockerEnvironmentTagVersion) }}
          