name: Build a Docker image

on: 
  workflow_call:
    inputs:
      DockerImage:
        description: 'Docker image name use to store in a container'
        required: true
        type: string
      Registry:
        description: 'Name of the container registry'     
        required: true
        type: string
    secrets:
      CR_User:
        required: true
      CR_Password:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
     fullImagePath: ${{ steps.imageTag.outputs.fullImagePath }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: configs
          path: |
            ./Service/Configs
            ./deploy.yml
          retention-days: 90
          
      - name: Remove Folder
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./Service/Configs

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.Registry }}
          username: ${{ secrets.CR_User }}
          password: ${{ secrets.CR_Password }}

      - name: Build and publish the docker image.
        run: |
          docker build ./Service -f ./Dockerfile -t ${{ inputs.DockerImage }}
          docker push ${{ inputs.DockerImage }} 